<p><a href="${admin.url}">${lang('common', 'home', 'Home')}</a> &gt;&gt; 
% if id!='0':
    ${lang('common', 'edit_new_item', 'Edit item')}
%else:
    ${lang('common', 'add_new_item', 'Add new item')}
%endif 
</p>
<form method="post" action="${add_get_parameters(admin.url, op_admin=2, id=id)}">
    <h2>${lang('common', 'add_new_item', 'Add new item')}</h2>
    <span class="error">${model.query_error}</span>
    ${ form|n }
    <p><input type="submit" value="${lang('common', 'send', 'Send') }"></p>
</form>