<table class="table_list">
    {% if simplelist.yes_search %}
        
    {% endif %}
    <tr class="title_list">
        {% for field in simplelist.fields %}
        <td><a href="{{simplelist.url|add_get_parameters(field_order=simplelist.model.forms[field].name)}}">{{simplelist.model.forms[field].label}}</a></td>
        {% endfor %}
    </tr>
    {% for row in list %}
    <tr class="row_list">
        {% for field in simplelist.fields %}
            <td>{{row[field]}}</td>
        {% endfor %}
    </tr>
    {% endfor %}
</table>
<p>
{{pages}}
</p>