<table class="table_list">
    {% if simplelist.yes_search %}
    <div class="form">
    <form method="post" action="{{simplelist.url}}">
        <input type="text" name="search_text" value="">
    </form>
    </div>
    {% endif %}
    <tr class="title_list">
        {% for field in simplelist.fields %}
        <td><a href="{{simplelist.url|add_get_parameters(order_field=simplelist.model.forms[field].name, begin_page=simplelist.begin_page, order=simplelist.change_order[field])}}" class="{% if simplelist.order_field==field %}fa fa-arrow-circle-{{simplelist.order_class[simplelist.s['order']]}}{% endif %}">{{simplelist.model.forms[field].label}}</a></td>
        {% endfor %}
    </tr>
    {% for row in list %}
    <tr class="row_list">
        {% for field in simplelist.fields %}
            <td>{{row[field]}}</td>
        {% endfor %}
    </tr>
    {% endfor %}
</table>
<p>
{{pages}}
</p>