<!DOCTYPE html>
<html>
    <head>
    <title>{% block title %}{{'admin'|lang('login', 'Paramecio Login')}}{% endblock %}</title>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    {{ 'jquery.min.js'|add_js_home }}
    {{ 'admin/login.css'|add_css_home }}
    {{ 'font-awesome.min.css'|add_css_home }}
    {{ HeaderHTML.css_home()|safe }}
    {{ HeaderHTML.js_home()|safe }}
    {% block ajax %}
    {% endblock %}
    </head>
    <body>
        {% block content %}
        <form id="login">
            <div id="title">
                {{'admin'|lang('login', 'Paramecio Login')}}
            </div>
            {{ forms|safe }}
            <input type="submit" value="{{'common'|lang('login', 'Login')}}" class="submit" />
        </form>
        {% endblock %}
    </body>
</html>
